project:
  type: website

website:
  title: "Joshua Entrop"
  favicon: pictures/icon.png
  page-footer:
    center:
      - text: "<a href='/terms.html'>Terms</a> <br> &#169 Joshua Philipp Entrop 2024"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: visual
