project:
  type: website
  resources:
    - assets
    - rcode

website:
  title: "Joshua Entrop 👋"
  image: /pictures/icon.png
  favicon: /pictures/icon.png
  site-url: https://www.joshua-entrop.com
  description: "Joshua Entrop's personal website featuring his R blog"
  open-graph:
    locale: en_EN
    site-name: Quarto
  page-footer:
    center:
      - text: "<a href='/terms.html'>Terms</a> <br> &#169 Joshua Philipp Entrop 2025"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: software.qmd
        text: Software

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
