project:
  type: website

website:
  title: "Joshua Entrop"
  favicon: pictures/icon.png
  site-url: https://www.joshua-entrop.com
  description: "Joshua Entrop's personal website featuring his R blog"
  page-footer:
    center:
      - text: "<a href='/terms.html'>Terms</a> <br> &#169 Joshua Philipp Entrop 2024"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
    right:
      - href: index.qmd
        text: EN
      - href: index.de.qmd
        text: DE
      - href: index.sv.qmd
        text: SV


format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
